"""Model cards, written from the results of the run that produced them.

Each card covers: purpose, data, features, validation scheme, results against
the baseline, limitations, and what the model must not be used for. Every
number in a card is read from the result tables; none is typed by hand, so a
card cannot drift from the stored results.
"""

from pathlib import Path

import pandas as pd

from config.settings import DOCS_DIR

CARDS_DIR = DOCS_DIR / "model_cards"

NOT_FOR = """## What this must not be used for

- Predicting prices or the direction of returns, or timing trades.
- Selecting, recommending or ranking securities. FinSight is an analytics tool, not investment advice.
- Any decision where the limitations above would matter and have not been checked on newer data.
"""


def header(title: str, context: dict) -> str:
    return (f"# Model card: {title}\n\n"
            f"- Generated by `python scripts/run_ml.py` (seed {context['seed']}); "
            "every figure below is read from that run's stored results.\n"
            f"- Data snapshot id: `{context['snapshot']}` "
            f"(prices {context['price_start']} to {context['price_end']}, "
            f"{context['n_companies']} companies)\n")


def markdown_table(frame: pd.DataFrame) -> str:
    lines = ["| " + " | ".join(str(c) for c in frame.columns) + " |",
             "|" + "---|" * len(frame.columns)]
    lines += ["| " + " | ".join(str(v) for v in row) + " |" for row in frame.itertuples(index=False)]
    return "\n".join(lines)


def pct(value, decimals=1) -> str:
    return "N/A" if value is None or pd.isna(value) else f"{value * 100:.{decimals}f}%"


def signed(value, decimals=1) -> str:
    return "N/A" if value is None or pd.isna(value) else f"{value:+.{decimals}f}%"


# --------------------------------------------------------------- volatility ----

def volatility_card(result: dict, context: dict) -> str:
    comparison, dm, folds, params = (result["comparison"], result["dm"], result["folds"],
                                     result["params"])
    sections = [header("Volatility forecasting", context)]
    sections.append(f"""## Purpose

Forecast each stock's realized volatility over the next {' and '.join(str(h) for h in params['horizons'])}
trading days, for risk measurement, and test whether a model does better than the standard naive
forecasts. Volatility is persistent and therefore forecastable; returns are not, and this model
does not attempt to forecast them.

## Data

- Daily adjusted close, high, low and volume for {params['tickers']} companies and the Nifty 50,
  from PostgreSQL (source: Yahoo Finance via yfinance). Placeholder rows are excluded.
- Target: realized variance over t+1 .. t+h, the mean of squared daily returns. Reported as
  annualized volatility (x sqrt(252)).

## Forecasters

| Name | Kind | Definition |
|---|---|---|
| `hist_21` | Baseline | Trailing 21-day realized variance |
| `ewma` | Baseline | RiskMetrics EWMA, lambda = {params['ewma_lambda']} |
| `garch` | Model | {params['garch']}; forecast variance averaged over the horizon |
| `ridge` | Model | Ridge regression (alpha = {params['ridge_alpha']}) on standardized features, pooled across companies |
| `gbm` | Model | Gradient-boosted trees ({', '.join(f'{k}={v}' for k, v in params['gbm'].items())}), pooled |

## Features (ridge and gbm)

`{'`, `'.join(params['features'])}`

Lagged realized variance over 1, 5, 21 and 63 days, the latest absolute return, volume relative to
its 21-day mean, Parkinson range-based variance over 5 and 21 days, and Nifty 50 realized variance
over 5 and 21 days. The models predict log realized variance; the forecast is exp(prediction +
half the training residual variance), the mean of a log-normal.

**Leakage controls.** Every feature at date t uses only data up to t (trailing windows). Scaling
is fitted on training rows only. Unit tests alter all data after a date and check that features
and every model's forecasts up to that date are unchanged.

## Validation

Walk-forward with an expanding window: {params['initial_train_days']} trading days before the
first test block, then blocks of {params['test_block_days']} days. Models are refitted at the start
of each block using only earlier data, and the last h training rows are purged so no training
target overlaps a test period. Random K-fold is never used. All forecasters are scored on one
common set of rows.
""")
    for horizon in sorted(folds["horizon"].unique()):
        rows = folds[folds["horizon"] == horizon]
        sections.append(f"- Horizon {horizon}: {len(rows)} folds, test dates "
                        f"{str(rows['test_start'].min())[:10]} to "
                        f"{str(rows['test_end'].max())[:10]}, "
                        f"{int(rows['test_rows'].sum()):,} forecasts.")

    sections.append("\n## Results against the baselines\n\n"
                    "RMSE and MAE are in annualized volatility (0.11 = 11 percentage points). "
                    "QLIKE is on variance; lower is better for all three. \"Change\" is relative "
                    "to the best baseline for that metric; negative means lower loss. "
                    "\"Fold mean ± sd\" shows variation across walk-forward folds.\n")
    for horizon in sorted(comparison["horizon"].unique()):
        rows = comparison[comparison["horizon"] == horizon]
        table = pd.DataFrame({
            "Metric": rows["metric"].str.upper(),
            "Forecaster": rows["model"] + " (" + rows["kind"] + ")",
            "Pooled": rows["value"].map(lambda v: f"{v:.4f}"),
            "Change vs best baseline": [
                "best baseline" if m == b else signed(c)
                for m, b, c in zip(rows["model"], rows["best_baseline"],
                                   rows["change_vs_best_baseline_pct"])],
            "Fold mean ± sd": [f"{m:.4f} ± {s:.4f}"
                               for m, s in zip(rows["fold_mean"], rows["fold_std"])],
            "Folds better than best baseline": [
                "-" if m == b else f"{w} of {n}"
                for m, b, w, n in zip(rows["model"], rows["best_baseline"],
                                      rows["folds_beating_best_baseline"], rows["folds"])],
        })
        sections.append(f"### {horizon}-day horizon\n\n{markdown_table(table)}\n")

    sections.append("### Diebold-Mariano tests (QLIKE loss, against the best baseline)\n\n"
                    "A negative statistic means lower loss than the benchmark. The pooled test "
                    "averages the loss difference across companies for each date and uses h-1 "
                    "Newey-West lags with the Harvey-Leybourne-Newbold correction.\n")
    table = pd.DataFrame({
        "Horizon": dm["horizon"], "Forecaster": dm["model"], "Benchmark": dm["benchmark"],
        "DM statistic": dm["dm_statistic"].map(lambda v: f"{v:+.2f}"),
        "p-value": dm["p_value"].map(lambda v: f"{v:.4f}"),
        "Companies significantly better (5%)": [
            f"{b} of {t}" for b, t in zip(dm["tickers_significantly_better"],
                                          dm["tickers_tested"])],
        "Significantly worse": dm["tickers_significantly_worse"],
    })
    sections.append(markdown_table(table) + "\n")

    best = {}
    for horizon in sorted(comparison["horizon"].unique()):
        rows = comparison[(comparison["horizon"] == horizon) & (comparison["metric"] == "qlike")
                          & (comparison["kind"] == "model")]
        top = rows.loc[rows["change_vs_best_baseline_pct"].idxmin()]
        test = dm[(dm["horizon"] == horizon) & (dm["model"] == top["model"])].iloc[0]
        verdict = ("beats" if top["change_vs_best_baseline_pct"] < 0 and test["p_value"] < 0.05
                   else "does not beat")
        best[horizon] = (f"- **{horizon}-day:** the best model by QLIKE is `{top['model']}`, which "
                         f"{verdict} the best baseline (`{top['best_baseline']}`): QLIKE "
                         f"{signed(top['change_vs_best_baseline_pct'])}, lower in "
                         f"{top['folds_beating_best_baseline']} of {top['folds']} folds, "
                         f"DM p = {test['p_value']:.4f}; significantly better for "
                         f"{test['tickers_significantly_better']} of {test['tickers_tested']} "
                         "companies individually.")
    sections.append("### Reading the results\n\n" + "\n".join(best.values()) + "\n")

    sections.append(f"""## Limitations

- **One market regime sample.** The test period is about three years of one market. The ranking
  of forecasters may not hold in a different volatility regime.
- **The target is a noisy proxy.** Realized variance from daily returns over 5 days is a rough
  estimate of the true variance; QLIKE is reported because it is robust to that noise.
- **Pooled coefficients.** Ridge and gbm use one set of parameters for all companies, which helps
  with limited history but ignores company-specific dynamics. The pooled improvement is not
  significant for every company individually (see the per-company counts above).
- **No hyperparameter search.** Ridge alpha and the tree settings are fixed, conventional values
  and were not tuned, so the test results are not optimistically selected. Tuning might help.
- **Overlapping forecasts.** Daily h-day forecasts overlap; the DM test allows for that, but the
  effective sample is smaller than the row count suggests.
- **GARCH assumes normal errors** and is refitted quarterly, not daily.
- **Survivorship.** The universe is 25 large companies listed today.

{NOT_FOR}""")
    return "\n".join(sections)


# --------------------------------------------------------------- clustering ----

def clustering_card(result: dict, context: dict) -> str:
    summary, stability, params = result["summary"], result["stability"], result["params"]
    selection = result["selection"].pivot(index="k", columns="method", values="silhouette")
    inertia = result["selection"][result["selection"]["method"] == "kmeans"].set_index("k")[
        "inertia"]
    choice = pd.DataFrame({
        "k": selection.index,
        "K-means silhouette": selection["kmeans"].map(lambda v: f"{v:.3f}"),
        "K-means inertia (elbow)": inertia.reindex(selection.index).map(lambda v: f"{v:.1f}"),
        "Hierarchical silhouette": selection["hierarchical"].map(lambda v: f"{v:.3f}"),
    })
    sections = [header("Peer clustering", context)]
    sections.append(f"""## Purpose

Check whether data-driven groups of companies match the sector labels used as peer groups in the
comparable-company analysis. Descriptive: it describes the last five years, it does not predict.

## Data

{params['n_companies']} companies, {params['n_days']:,} trading days of returns on dates common to
all of them, and each company's latest annual fundamentals from `core.metrics`.

## Features and methods

| Method | Input | Notion of similarity |
|---|---|---|
| K-means ({params['kmeans_n_init']} initializations) | Standardized `{'`, `'.join(params['features'])}` | Companies with similar risk and business profile |
| Hierarchical, {params['linkage']} linkage | Distance = {params['distance']} of daily returns | Stocks whose prices move together |

Fundamental features are limited to ones that apply to every sector type, so banks are clustered
on the same features as everyone else (EBITDA margin and debt/equity are left out). Missing
fundamentals are replaced by the cross-sectional median: {len(params['imputed'])} value(s) in this
run{': ' + ', '.join(f'{t} {f}' for t, f in params['imputed']) if params['imputed'] else ''}.
The first two principal components, used only for plotting, explain
{pct(sum(params['pca_explained_variance']))} of the feature variance.

## Choosing k

k is chosen by the highest silhouette score over k = {params['k_range'][0]}..{params['k_range'][1]};
K-means inertia is listed for the elbow.

{markdown_table(choice)}

Chosen: **k = {summary['kmeans']['k']}** for K-means (silhouette {summary['kmeans']['silhouette']:.3f})
and **k = {summary['hierarchical']['k']}** for hierarchical clustering (silhouette
{summary['hierarchical']['silhouette']:.3f}). Silhouette scores of this size indicate weak-to-moderate
structure, and for K-means the scores for neighbouring k are close, so its k is not sharply
determined.

## Results: agreement with sector labels

The adjusted Rand index (ARI) is 1 for identical groupings and about 0 for chance agreement.

| | K-means | Hierarchical |
|---|---|---|
| ARI vs sector, at the chosen k | {summary['kmeans']['ari_vs_sector']:.3f} | {summary['hierarchical']['ari_vs_sector']:.3f} |
| ARI vs sector, at k = number of sectors ({params['n_sectors']}) | {summary['kmeans']['ari_vs_sector_at_sector_count']:.3f} | {summary['hierarchical']['ari_vs_sector_at_sector_count']:.3f} |

ARI between the two methods' groupings: {summary['kmeans_vs_hierarchical_ari']:.3f}.

**K-means, clusters by sector**

{markdown_table(result['crosstab']['kmeans'].reset_index())}

{chr(10).join('- ' + line for line in result['mismatches']['kmeans'])}

**Hierarchical, clusters by sector**

{markdown_table(result['crosstab']['hierarchical'].reset_index())}

{chr(10).join('- ' + line for line in result['mismatches']['hierarchical'])}

## Stability

Each resample redraws the trading days in blocks of {params['bootstrap_block_days']} days
({params['bootstrap_resamples']} resamples), re-clusters with the same k, and is compared with the
full-sample clusters.

| | K-means | Hierarchical |
|---|---|---|
| Bootstrap ARI vs full sample, mean | {stability['kmeans']['bootstrap_mean_ari']:.3f} | {stability['hierarchical']['bootstrap_mean_ari']:.3f} |
| Bootstrap ARI, 5th to 95th percentile | {stability['kmeans']['bootstrap_p05_ari']:.3f} to {stability['kmeans']['bootstrap_p95_ari']:.3f} | {stability['hierarchical']['bootstrap_p05_ari']:.3f} to {stability['hierarchical']['bootstrap_p95_ari']:.3f} |
| First half vs full sample | {stability['kmeans']['first_half_vs_full_ari']:.3f} | {stability['hierarchical']['first_half_vs_full_ari']:.3f} |
| Second half vs full sample | {stability['kmeans']['second_half_vs_full_ari']:.3f} | {stability['hierarchical']['second_half_vs_full_ari']:.3f} |
| First half vs second half | {stability['kmeans']['first_vs_second_half_ari']:.3f} | {stability['hierarchical']['first_vs_second_half_ari']:.3f} |

## Limitations

- **25 companies, 5 per sector.** A single company changing cluster moves the ARI noticeably.
- **The universe was chosen by sector**, five well-known companies from each. Agreement between
  return-based clusters and sectors is partly a property of that selection and would be weaker in
  a broader, less tidy universe.
- **Stability is measured on resampled returns only.** Fundamentals are held fixed, and they come
  from one fiscal year.
- **K-means depends on the feature set and scaling.** A different, equally reasonable set of
  features would give different clusters; the bootstrap range above shows how loosely they hold.
- **Infosys fundamentals are in USD** (ratios are currency-invariant, growth is in USD).

{NOT_FOR}""")
    return "\n".join(sections)


# ------------------------------------------------------------- stats tests ----

def stats_tests_card(result: dict, context: dict) -> str:
    summary, params = result["summary"], result["params"]
    normal, sharpe, corr = summary["normality"], summary["sharpe"], summary["correlation"]
    stress = summary["stress_correlation"]
    sector_rows = pd.DataFrame([
        {"Variable": name, "H": f"{v['h_statistic']:.2f}", "p-value": f"{v['p_value']:.4f}",
         "Epsilon-squared": f"{v['epsilon_squared']:.2f}", "n": v["n"],
         "Pairs significant after BH": f"{v['pairs_significant_after_bh']} of {v['pairs_tested']}",
         "Largest pairwise |rank-biserial|": f"{v['largest_pairwise_effect']:.2f}"}
        for name, v in summary["sector_differences"].items()])
    sections = [header("Statistical tests", context)]
    sections.append(f"""This is not a predictive model. It is the set of tests behind the
"Statistical tests" panel of the Data Science Lab, documented in the same format.

## Purpose

Attach uncertainty to the figures the platform reports: are returns normal, how precisely is a
Sharpe ratio or a peer median known, which correlations are distinguishable from zero, and do
sectors differ.

## Data

Daily returns on {params['n_days']:,} dates common to all tickers, for {params['n_companies']}
companies and the Nifty 50; latest metrics from `core.metrics`. Risk-free rate
{pct(params['risk_free_rate'], 4)}.

## Methods

| Question | Test | Uncertainty reported |
|---|---|---|
| Are daily returns normal? | Jarque-Bera, with skewness and excess kurtosis | p-values, Benjamini-Hochberg adjusted |
| How precise is a Sharpe ratio? | Moving-block bootstrap, {params['sharpe_block_days']}-day blocks, {params['bootstrap_resamples']:,} resamples | 95% percentile interval |
| How precise is a peer median? | Bootstrap of the peer group | 95% percentile interval |
| Which correlations differ from zero? | Pearson correlation t-test for every pair | Benjamini-Hochberg adjusted p-values; r-squared as effect size |
| Do sectors differ? | Kruskal-Wallis, then pairwise Mann-Whitney U | Epsilon-squared and rank-biserial effect sizes; BH-adjusted pairwise p-values |
| Do correlations rise in stressed markets? | Difference in mean pairwise correlation, top-quartile market volatility vs the rest | Block-bootstrap 95% interval |

All tests use a 5% level. Multiple comparisons are corrected with {params['multiple_comparison_correction']}.

## Results

**Return distributions.** Normality is rejected for {normal['rejected_at_5pct_after_bh']} of
{normal['series_tested']} series after correction. Excess kurtosis ranges from
{normal['excess_kurtosis_min']:.2f} to {normal['excess_kurtosis_max']:.2f} (median
{normal['excess_kurtosis_median']:.2f}; 0 for a normal distribution) and skewness from
{normal['skewness_min']:.2f} to {normal['skewness_max']:.2f}. On average
{pct(normal['mean_share_beyond_3_sd'], 2)} of days are more than three standard deviations from
the mean, against 0.27% under normality: returns have fat tails, so a volatility figure alone
understates how often large moves occur.

**Sharpe ratios.** The 95% interval excludes zero for {sharpe['intervals_excluding_zero']} of
{sharpe['series']} series; the median interval is {sharpe['median_interval_width']:.2f} wide. About
five years of daily returns do not pin down a Sharpe ratio, and differences between the Sharpe
ratios shown in the app should not be read as established.

**Correlations.** Of {corr['pairs']} company pairs, {corr['significant_unadjusted']} have p < 0.05
before correction and {corr['significant_after_bh']} after. Correlations range from
{corr['min']:.2f} to {corr['max']:.2f} (median {corr['median']:.2f}). With this many observations
even a small correlation is statistically distinguishable from zero, so significance says little
here; the size of the correlation is what matters.

**Sector differences.**

{markdown_table(sector_rows)}

Epsilon-squared is the share of rank variance explained by sector. With five companies per sector
the smallest possible two-sided Mann-Whitney p-value is 0.0079, so few pairs can survive
correction for ten comparisons however large the difference; the effect sizes carry the
information.

**Stress and correlation.** Mean pairwise correlation is {stress['stressed']:.3f} on the
{stress['stressed_days']} stressed days and {stress['calm']:.3f} on the {stress['calm_days']} calm
days: a difference of {stress['difference']:+.3f} (95% interval {stress['ci_low']:+.3f} to
{stress['ci_high']:+.3f}), which {'excludes' if stress['excludes_zero'] else 'does not exclude'}
zero. Diversification across these stocks was weaker when the market was volatile.

**Peer medians.** {summary['peer_median_intervals']} bootstrap intervals are stored. With five
companies in a group an interval can only take values that occur in the group, so it mostly spans
the group's range.

## Limitations

- **Small cross-sections.** Sector tests have 25 companies in 5 groups; they can detect only large
  differences, and a non-significant result is not evidence of no difference.
- **The stress threshold uses the whole sample**, so the stressed/calm split describes the past
  and could not have been applied in real time.
- **Block length is a choice.** Sharpe intervals use 21-day blocks; other reasonable lengths
  give somewhat different widths.
- **Pearson correlation** measures linear co-movement of same-day returns only.
- **Jarque-Bera with over a thousand observations** rejects for small departures from
  normality; the kurtosis and tail-frequency figures show how large the departure is.

{NOT_FOR}""")
    return "\n".join(sections)


# ------------------------------------------------------------------ regimes ----

def regimes_card(result: dict, context: dict) -> str:
    summary, params = result["summary"], result["params"]

    def regime_table(frame: pd.DataFrame) -> str:
        return markdown_table(pd.DataFrame({
            "Regime": frame["regime"], "Days": frame["days"],
            "Share of days": frame["share_of_days"].map(pct),
            "Nifty 50 volatility": frame["market_volatility"].map(pct),
            "Mean stock volatility": frame["mean_stock_volatility"].map(pct),
            "Mean pairwise correlation": frame["mean_pairwise_correlation"].map(
                lambda v: f"{v:.3f}"),
        }))

    return "\n".join([header("Market regime detection", context), f"""## Purpose

Describe the last five years of the Nifty 50 as alternating calm and turbulent periods, and show
how volatility and correlation differed between them. **Descriptive segmentation only.**

## Data

{params['n_days']:,} daily Nifty 50 returns, and company returns on the same dates.

## Method

{params['model']}, fitted by maximum likelihood (statsmodels). Each day gets a smoothed probability
of being in the high-variance state; a day is labelled turbulent when that probability exceeds 0.5.
As a transparent comparison, a rule labels a day turbulent when {params['threshold_rule']}.

## Validation

There is no ground truth for a regime, so there is no accuracy to report and no baseline to beat.
The model is checked for convergence ({'converged' if summary['converged'] else 'DID NOT CONVERGE'})
and compared with the threshold rule: the two agree on {pct(summary['agreement_with_threshold_rule'])}
of days.

## Results

Estimated annualized volatility: {pct(summary['volatility']['calm'])} in the calm state and
{pct(summary['volatility']['turbulent'])} in the turbulent state. Expected duration:
{summary['expected_duration_days']['calm']:.0f} trading days calm,
{summary['expected_duration_days']['turbulent']:.0f} turbulent. {pct(summary['turbulent_share_of_days'])}
of days are labelled turbulent. Log-likelihood {summary['log_likelihood']:.1f}, AIC {summary['aic']:.1f}.

**By Markov-switching regime**

{regime_table(result['by_regime'])}

**By threshold rule**

{regime_table(result['by_threshold_regime'])}

## Limitations

- **Smoothed probabilities use the whole sample.** A day's label depends on what happened
  afterwards, so the labels could not have been known at the time.
- **Two states are assumed**, not found. The data were not asked whether three would fit better.
- **Higher correlation in the turbulent state is partly mechanical:** correlation estimates rise
  with volatility even when the underlying relationship is unchanged.
- **One index, five years.** Few turbulent episodes are in the sample.

## What this must not be used for

- **It is not a trading or timing signal.** The labels are fitted with hindsight.
- Predicting when the next turbulent period will start or end.
- Selecting, recommending or ranking securities. FinSight is an analytics tool, not investment advice.
"""])


# ---------------------------------------------------------------- anomalies ----

def anomaly_card(result: dict, context: dict) -> str:
    summary, params = result["summary"], result["params"]
    counts = summary["flagged_by"]
    overlap = pd.DataFrame({
        "Method A": result["overlap"]["method_a"], "Method B": result["overlap"]["method_b"],
        "Flagged by both": result["overlap"]["both"], "Only A": result["overlap"]["only_a"],
        "Only B": result["overlap"]["only_b"],
        "Jaccard overlap": result["overlap"]["jaccard"].map(lambda v: f"{v:.3f}"),
    })
    observations = summary["observations"]
    return "\n".join([header("Anomaly detection comparison (Isolation Forest)", context),
                      f"""## Purpose

Compare a machine-learning anomaly detector with the two statistical rules used elsewhere in
FinSight, on the same daily market data, and report how far they agree. Every flag is worded
"Potential data anomaly detected": a prompt to look at a data point, never a statement about a
company.

## Data

{observations:,} company-days of returns and volume (placeholder rows excluded, first
{params['rolling_window']} days of each series used as history).

## Features

`{'`, `'.join(params['features'])}`: each day's return and log volume expressed as a modified
z-score against that stock's previous {params['rolling_window']} days, plus the absolute return.
The rolling scores use only earlier data, the same as the statistical rules.

## Methods compared

| Method | Rule |
|---|---|
| IQR | Return or log volume outside {params['iqr_multiplier']:g}x IQR fences of its prior {params['rolling_window']} days |
| Modified z-score | Absolute modified z-score of return or log volume above {params['modified_zscore_threshold']:g} |
| Isolation Forest | {params['n_estimators']} trees, contamination {pct(params['contamination'])}, seed {params['seed']} |

The contamination rate was fixed at {pct(params['contamination'])} in advance. It was not set to
match the number of points the statistical rules flag.

## Validation

There are no labels saying which days are truly anomalous, so no accuracy can be computed and
there is no baseline to beat. What can be measured is agreement between methods.

## Results

| Method | Flagged | Share of observations |
|---|---|---|
| IQR | {counts['iqr']:,} | {pct(counts['iqr'] / observations, 2)} |
| Modified z-score | {counts['modified_zscore']:,} | {pct(counts['modified_zscore'] / observations, 2)} |
| Isolation Forest | {counts['isolation_forest']:,} | {pct(counts['isolation_forest'] / observations, 2)} |

{markdown_table(overlap)}

{summary['flagged_by_all_three']:,} company-days are flagged by all three methods,
{summary['flagged_by_exactly_two']:,} by exactly two and {summary['flagged_by_exactly_one']:,} by
only one. {summary['isolation_forest_only']:,} are flagged by the Isolation Forest alone. The
points flagged by all three are the ones most worth inspecting; a sample is examined by hand in
`notebooks/07_anomalies_and_regimes`.

## Limitations

- **The forest is fitted on the whole sample** (it is unsupervised and descriptive), so, unlike
  the two rules, its flags are not strictly real-time. Its input features are leakage-free.
- **Its flag count is set by the contamination parameter**, so "the forest flags 2% of days" is an
  input, not a finding. Only which days it picks is informative.
- **The methods share inputs**, so agreement between them is expected and is not independent
  confirmation.
- **Fat tails.** All three flag far more days than a normal distribution would predict; most are
  genuine large moves around news, not data errors.

## What this must not be used for

- Concluding anything about a company's conduct. A flag marks an unusual data point only.
- Removing data automatically. Nothing is deleted on the basis of a flag.
- Selecting, recommending or ranking securities. FinSight is an analytics tool, not investment advice.
"""])


CARDS = {
    "volatility": ("volatility_forecasting.md", volatility_card),
    "clustering": ("peer_clustering.md", clustering_card),
    "stats_tests": ("statistical_tests.md", stats_tests_card),
    "regimes": ("regime_detection.md", regimes_card),
    "anomaly_comparison": ("anomaly_isolation_forest.md", anomaly_card),
}


def write_all(results: dict, context: dict, cards_dir: Path | None = None) -> list[Path]:
    """Write a card for every task present in `results`. Returns the paths written."""
    cards_dir = cards_dir or CARDS_DIR
    cards_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for task, (filename, build) in CARDS.items():
        if task in results:
            path = cards_dir / filename
            path.write_text(build(results[task], context), encoding="utf-8")
            written.append(path)
    return written
